const productos = [
  // ========== CELULARES ==========
  {
    id: "iphone-15-pro-256",
    categoria: "Celulares",
    nombre: "iPhone 15 Pro",
    especificaciones: "Chip A17 Pro | 256GB | Camara 48MP",
    precioPEN: 5499,
    colores: ["#3B4C5A", "#F5F5DC", "#1A1C72"],
    imagen: "assets/Celulares/iPhone_15_Pro/imagen_1.png",
  },
  {
    id: "iphone-15-pro-512",
    categoria: "Celulares",
    nombre: "iPhone 15 Pro",
    especificaciones: "Chip A17 Pro | 512GB | Camara 48MP",
    precioPEN: 10999,
    colores: ["#3B4C5A", "#F5F5DC"],
    imagen: "assets/Celulares/iPhone_15_Pro/imagen_2.png",
  },
  {
    id: "samsung-galaxy-s24-ultra-256",
    categoria: "Celulares",
    nombre: "Samsung Galaxy S24 Ultra",
    especificaciones: "Snapdragon 8 Gen 3 | 256GB | Camara 200MP",
    precioPEN: 7499,
    colores: ["#2C2C2C", "#E8D5B7", "#4A6741"],
    imagen: "assets/Celulares/Samsung_Galaxy_S24_Ultra/imagen_1.png",
  },
  {
    id: "samsung-galaxy-s24-ultra-512",
    categoria: "Celulares",
    nombre: "Samsung Galaxy S24 Ultra",
    especificaciones: "Snapdragon 8 Gen 3 | 512GB | Camara 200MP",
    precioPEN: 8999,
    colores: ["#2C2C2C", "#E8D5B7"],
    imagen: "assets/Celulares/Samsung_Galaxy_S24_Ultra/imagen_2.png",
  },
  {
    id: "xiaomi-14-256",
    categoria: "Celulares",
    nombre: "Xiaomi 14",
    especificaciones: "Snapdragon 8 Gen 3 | 256GB | Camara Leica",
    precioPEN: 4299,
    colores: ["#1A1A2E", "#F0E68C", "#4A90A4"],
    imagen: "assets/Celulares/Xiaomi_14/imagen_1.png",
  },
  {
    id: "xiaomi-14-512",
    categoria: "Celulares",
    nombre: "Xiaomi 14",
    especificaciones: "Snapdragon 8 Gen 3 | 512GB | Camara Leica",
    precioPEN: 5199,
    colores: ["#1A1A2E", "#F0E68C", "#4A90A4"],
    imagen: "assets/Celulares/Xiaomi_14/imagen_2.png",
  },

  // ========== LAPTOPS ==========
  {
    id: "macbook-air-m3-256",
    categoria: "Laptops",
    nombre: "MacBook Air M3",
    especificaciones: 'Chip M3 | 8GB RAM | 256GB SSD | Pantalla 13.6"',
    precioPEN: 9499,
    colores: ["#C0C0C0", "#2C2C2E", "#E8D5C4"],
    imagen: "assets/Laptops/MacBook_Air_M3/imagen_1.png",
  },
  {
    id: "macbook-air-m3-512",
    categoria: "Laptops",
    nombre: "MacBook Air M3",
    especificaciones: 'Chip M3 | 16GB RAM | 512GB SSD | Pantalla 13.6"',
    precioPEN: 11999,
    colores: ["#C0C0C0", "#2C2C2E"],
    imagen: "assets/Laptops/MacBook_Air_M3/imagen_2.png",
  },
  {
    id: "lenovo-thinkpad-x1-carbon",
    categoria: "Laptops",
    nombre: "Lenovo ThinkPad X1 Carbon",
    especificaciones: 'Intel i7 | 16GB RAM | 512GB SSD | Pantalla 14"',
    precioPEN: 8799,
    colores: ["#1A1A1A"],
    imagen: "assets/Laptops/Lenovo_ThinkPad_X1_Carbon/imagen_1.png",
  },
  {
    id: "hp-pavilion-15-ryzen5",
    categoria: "Laptops",
    nombre: "HP Pavilion 15",
    especificaciones: 'AMD Ryzen 5 | 8GB RAM | 512GB SSD | Pantalla 15.6"',
    precioPEN: 4999,
    colores: ["#B8C4CC", "#2C2C2E"],
    imagen: "assets/Laptops/HP_Pavilion_15/imagen_1.png",
  },
  {
    id: "hp-pavilion-15-ryzen7",
    categoria: "Laptops",
    nombre: "HP Pavilion 15",
    especificaciones: 'AMD Ryzen 7 | 16GB RAM | 1TB SSD | Pantalla 15.6"',
    precioPEN: 6499,
    colores: ["#B8C4CC", "#2C2C2E"],
    imagen: "assets/Laptops/HP_Pavilion_15/imagen_2.png",
  },

  // ========== AUDIFONOS ==========
  {
    id: "airpods-pro-2-usbc",
    categoria: "Audifonos",
    nombre: "Apple AirPods Pro 2",
    especificaciones: "Cancelacion de ruido activa | USB-C | H2 Chip",
    precioPEN: 1899,
    colores: ["#FFFFFF"],
    imagen: "assets/Audifonos/Apple_AirPods_Pro_2/imagen_1.png",
  },
  {
    id: "sony-wh-1000xm5",
    categoria: "Audifonos",
    nombre: "Sony WH-1000XM5",
    especificaciones: "Cancelacion de ruido | 30h bateria | LDAC",
    precioPEN: 2499,
    colores: ["#1A1A1A", "#C0C0C0", "#E8D5C4"],
    imagen: "assets/Audifonos/Sony_WH-1000XM5/imagen_1.png",
  },
  {
    id: "jbl-tune-510bt",
    categoria: "Audifonos",
    nombre: "JBL Tune 510BT",
    especificaciones: "Bluetooth 5.0 | 40h bateria | PureBass",
    precioPEN: 349,
    colores: ["#1A1A2E", "#FFFFFF", "#4169E1"],
    imagen: "assets/Audifonos/JBL_Tune_510BT/imagen_1.png",
  },
  {
    id: "jbl-charge-5",
    categoria: "Audifonos",
    nombre: "JBL Charge 5",
    especificaciones: "Bluetooth 5.1 | 20h bateria | IP67 | Powerbank",
    precioPEN: 699,
    colores: ["#1A1A2E", "#2E8B57", "#B22222"],
    imagen: "assets/Audifonos/JBL_Charge_5/imagen_1.png",
  },
  {
    id: "bose-qc-ultra",
    categoria: "Audifonos",
    nombre: "Bose QuietComfort Ultra",
    especificaciones: "Cancelacion de ruido | Immersive Audio | 24h bateria",
    precioPEN: 3299,
    colores: ["#1A1A2E", "#C0C0C0", "#E8D5C4"],
    imagen: "assets/Audifonos/Bose_QC_Ultra/imagen_1.png",
  },

  // ========== ACCESORIOS ==========
  {
    id: "cargador-magsafe",
    categoria: "Accesorios",
    nombre: "Cargador MagSafe",
    especificaciones: "Carga inalambrica 15W | Compatible iPhone",
    precioPEN: 299,
    colores: ["#FFFFFF"],
    imagen: "assets/Accesorios/Cargador_MagSafe/imagen_1.png",
  },
  {
    id: "funda-iphone-15-pro",
    categoria: "Accesorios",
    nombre: "Funda iPhone 15 Pro",
    especificaciones: "Silicona | MagSafe | Proteccion completa",
    precioPEN: 149,
    colores: ["#1A1A2E", "#4169E1", "#2E8B57"],
    imagen: "assets/Accesorios/Funda_iPhone_15_Pro/imagen_1.png",
  },
   {
    id: "logitech-mx-master-3s",
    categoria: "Accesorios",
    nombre: "Logitech MX Master 3S",
    especificaciones: "Inalambrico | 8K DPI | USB-C | Silence Click",
    precioPEN: 649,
    colores: ["#1A1A2E", "#C0C0C0"],
    imagen: "assets/Accesorios/Logitech_MX_Master_3S/imagen_1.png",
  },
  {
    id: "anker-powercore-20000",
    categoria: "Accesorios",
    nombre: "Anker PowerCore 20000",
    especificaciones: "Powerbank 20000mAh | Carga rapida 20W",
    precioPEN: 249,
    colores: ["#1A1A2E", "#FFFFFF"],
    imagen: "assets/Accesorios/Anker_PowerCore_20000/imagen_1.png",
  },
  {
    id: "samsung-monitor-27",
    categoria: "Accesorios",
    nombre: 'Samsung Monitor 27" 4K',
    especificaciones: "4K UHD | IPS | USB-C | 60Hz",
    precioPEN: 1899,
    colores: ["#1A1A2E", "#C0C0C0"],
    imagen: "assets/Accesorios/Samsung_Monitor_27/imagen_1.png",
  },

  // ========== SMARTWATCHES ==========
  {
    id: "apple-watch-series-9-45",
    categoria: "Smartwatches",
    nombre: "Apple Watch Series 9",
    especificaciones: "S9 SiP | GPS | Pantalla Always-On | 45mm",
    precioPEN: 3499,
    colores: ["#C0C0C0", "#1A1A2E", "#FFB6C1"],
    imagen: "assets/Smartwatches/Apple_Watch_Series_9/imagen_1.png",
  },
  {
    id: "apple-watch-series-9-41",
    categoria: "Smartwatches",
    nombre: "Apple Watch Series 9",
    especificaciones: "S9 SiP | GPS | Pantalla Always-On | 41mm",
    precioPEN: 3199,
    colores: ["#C0C0C0", "#FFB6C1"],
    imagen: "assets/Smartwatches/Apple_Watch_Series_9/imagen_2.png",
  },
  {
    id: "samsung-galaxy-watch-6-44",
    categoria: "Smartwatches",
    nombre: "Samsung Galaxy Watch 6",
    especificaciones: "Exynos W930 | GPS | WearOS | 44mm",
    precioPEN: 2199,
    colores: ["#1A1A2E", "#C0C0C0"],
    imagen: "assets/Smartwatches/Samsung_Galaxy_Watch_6/imagen_1.png",
  },
  {
    id: "xiaomi-smart-band-8",
    categoria: "Smartwatches",
    nombre: "Xiaomi Smart Band 8",
    especificaciones: "Pantalla AMOLED | 16 dias bateria | GPS",
    precioPEN: 249,
    colores: ["#1A1A2E", "#C0C0C0", "#FFB6C1"],
    imagen: "assets/Smartwatches/Xiaomi_Smart_Band_8/imagen_1.png",
  },
  {
    id: "xiaomi-smart-band-8-nfc",
    categoria: "Smartwatches",
    nombre: "Xiaomi Smart Band 8",
    especificaciones: "Pantalla AMOLED | 16 dias bateria | NFC",
    precioPEN: 299,
    colores: ["#1A1A2E", "#C0C0C0"],
    imagen: "assets/Smartwatches/Xiaomi_Smart_Band_8/imagen_2.png",
  },

  // ========== TABLETS ==========
  {
    id: "ipad-air-m2",
    categoria: "Tablets",
    nombre: "iPad Air M2",
    especificaciones: 'Chip M2 | 64GB | Pantalla 11" Liquid Retina',
    precioPEN: 2999,
    colores: ["#C0C0C0", "#1A1A2E", "#E8D5C4"],
    imagen: "assets/Tablets/iPad_Air_M2/imagen_1.png",
  },
  {
    id: "samsung-galaxy-tab-s9",
    categoria: "Tablets",
    nombre: "Samsung Galaxy Tab S9",
    especificaciones: 'Snapdragon 8 Gen 2 | 128GB | AMOLED 11"',
    precioPEN: 3499,
    colores: ["#1A1A2E", "#C0C0C0"],
    imagen: "assets/Tablets/Samsung_Galaxy_Tab_S9/imagen_1.png",
  },

  // ========== GAMING ==========
  {
    id: "dualsense-edge",
    categoria: "Gaming",
    nombre: "PlayStation DualSense Edge",
    especificaciones: "Control pro | Back buttons | Stick removibles",
    precioPEN: 1299,
    colores: ["#FFFFFF", "#1A1A2E"],
    imagen: "assets/Gaming/DualSense_Edge/imagen_1.png",
  },
  {
    id: "xbox-controller",
    categoria: "Gaming",
    nombre: "Xbox Wireless Controller",
    especificaciones: "Bluetooth | USB-C | Compatible PC/Xbox",
    precioPEN: 349,
    colores: ["#1A1A2E", "#FFFFFF", "#2E8B57"],
    imagen: "assets/Gaming/Xbox_Controller/imagen_1.png",
  },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = productos;
}
