const productos = [
  // ========== CELULARES ==========
  {
    id: "iphone-15-pro-256",
    categoria: "Celulares",
    nombre: "iPhone 15 Pro",
    especificaciones: "Chip A17 Pro | 256GB | Camara 48MP",
    precioPEN: 1,
    colores: ["#3B4C5A", "#F5F5DC", "#1A1C72"],
    imagen: "assets/iPhone_15_Pro/imagen_1.jpg",
  },
  {
    id: "iphone-15-pro-512",
    categoria: "Celulares",
    nombre: "iPhone 15 Pro",
    especificaciones: "Chip A17 Pro | 512GB | Camara 48MP",
    precioPEN: 10999,
    colores: ["#3B4C5A", "#F5F5DC"],
    imagen: "assets/iPhone_15_Pro/imagen_2.jpg",
  },
  {
    id: "samsung-galaxy-s24-ultra-256",
    categoria: "Celulares",
    nombre: "Samsung Galaxy S24 Ultra",
    especificaciones: "Snapdragon 8 Gen 3 | 256GB | Camara 200MP",
    precioPEN: 7499,
    colores: ["#2C2C2C", "#E8D5B7", "#4A6741"],
    imagen: "assets/Samsung_Galaxy_S24_Ultra/imagen_1.jpg",
  },
  {
    id: "samsung-galaxy-s24-ultra-512",
    categoria: "Celulares",
    nombre: "Samsung Galaxy S24 Ultra",
    especificaciones: "Snapdragon 8 Gen 3 | 512GB | Camara 200MP",
    precioPEN: 8999,
    colores: ["#2C2C2C", "#E8D5B7"],
    imagen: "assets/Samsung_Galaxy_S24_Ultra/imagen_2.jpg",
  },
  {
    id: "xiaomi-14-256",
    categoria: "Celulares",
    nombre: "Xiaomi 14",
    especificaciones: "Snapdragon 8 Gen 3 | 256GB | Camara Leica",
    precioPEN: 4299,
    colores: ["#1A1A2E", "#F0E68C", "#4A90A4"],
    imagen: "assets/Xiaomi_14/imagen_1.jpg",
  },
  {
    id: "xiaomi-14-512",
    categoria: "Celulares",
    nombre: "Xiaomi 14",
    especificaciones: "Snapdragon 8 Gen 3 | 512GB | Camara Leica",
    precioPEN: 5199,
    colores: ["#1A1A2E", "#4A90A4"],
    imagen: "assets/Xiaomi_14/imagen_2.jpg",
  },

  // ========== LAPTOPS ==========
  {
    id: "macbook-air-m3-256",
    categoria: "Laptops",
    nombre: "MacBook Air M3",
    especificaciones: 'Chip M3 | 8GB RAM | 256GB SSD | Pantalla 13.6"',
    precioPEN: 9499,
    colores: ["#C0C0C0", "#2C2C2E", "#E8D5C4"],
    imagen: "assets/MacBook_Air_M3/imagen_1.jpg",
  },
  {
    id: "macbook-air-m3-512",
    categoria: "Laptops",
    nombre: "MacBook Air M3",
    especificaciones: 'Chip M3 | 16GB RAM | 512GB SSD | Pantalla 13.6"',
    precioPEN: 11999,
    colores: ["#C0C0C0", "#2C2C2E"],
    imagen: "assets/MacBook_Air_M3/imagen_2.jpg",
  },
  {
    id: "lenovo-thinkpad-x1-carbon",
    categoria: "Laptops",
    nombre: "Lenovo ThinkPad X1 Carbon",
    especificaciones: 'Intel i7 | 16GB RAM | 512GB SSD | Pantalla 14"',
    precioPEN: 8799,
    colores: ["#1A1A1A"],
    imagen: "assets/Lenovo_ThinkPad_X1_Carbon/imagen_1.jpg",
  },
  {
    id: "hp-pavilion-15-ryzen5",
    categoria: "Laptops",
    nombre: "HP Pavilion 15",
    especificaciones: 'AMD Ryzen 5 | 8GB RAM | 512GB SSD | Pantalla 15.6"',
    precioPEN: 4999,
    colores: ["#B8C4CC", "#2C2C2E"],
    imagen: "assets/HP_Pavilion_15/imagen_1.jpg",
  },
  {
    id: "hp-pavilion-15-ryzen7",
    categoria: "Laptops",
    nombre: "HP Pavilion 15",
    especificaciones: 'AMD Ryzen 7 | 16GB RAM | 1TB SSD | Pantalla 15.6"',
    precioPEN: 6499,
    colores: ["#B8C4CC", "#2C2C2E"],
    imagen: "assets/HP_Pavilion_15/imagen_2.jpg",
  },

  // ========== AUDIFONOS ==========
  {
    id: "airpods-pro-2-usbc",
    categoria: "Audifonos",
    nombre: "Apple AirPods Pro 2",
    especificaciones: "Cancelacion de ruido activa | USB-C | H2 Chip",
    precioPEN: 1899,
    colores: ["#FFFFFF"],
    imagen: "assets/Apple_AirPods_Pro_2/imagen_1.jpg",
  },
  {
    id: "sony-wh-1000xm5",
    categoria: "Audifonos",
    nombre: "Sony WH-1000XM5",
    especificaciones: "Cancelacion de ruido | 30h bateria | LDAC",
    precioPEN: 2499,
    colores: ["#1A1A1A", "#C0C0C0", "#E8D5C4"],
    imagen: "assets/Sony_WH-1000XM5/imagen_1.jpg",
  },
  {
    id: "jbl-tune-510bt",
    categoria: "Audifonos",
    nombre: "JBL Tune 510BT",
    especificaciones: "Bluetooth 5.0 | 40h bateria | PureBass",
    precioPEN: 349,
    colores: ["#1A1A2E", "#FFFFFF", "#4169E1"],
    imagen: "assets/JBL_Tune_510BT/imagen_1.jpg",
  },
  
  // ========== ACCESORIOS ==========
  {
    id: "cargador-magsafe",
    categoria: "Accesorios",
    nombre: "Cargador MagSafe",
    especificaciones: "Carga inalambrica 15W | Compatible iPhone",
    precioPEN: 299,
    colores: ["#FFFFFF"],
    imagen: "assets/Cargador_MagSafe/imagen_1.jpg",
  },
  {
    id: "funda-iphone-15-pro",
    categoria: "Accesorios",
    nombre: "Funda iPhone 15 Pro",
    especificaciones: "Silicona | MagSafe | Proteccion completa",
    precioPEN: 149,
    colores: ["#1A1A2E", "#4169E1", "#2E8B57"],
    imagen: "assets/Funda_iPhone_15_Pro/imagen_1.jpeg",
  },
   {
    id: "logitech-mx-master-3s",
    categoria: "Accesorios",
    nombre: "Logitech MX Master 3S",
    especificaciones: "Inalambrico | 8K DPI | USB-C | Silence Click",
    precioPEN: 649,
    colores: ["#1A1A2E", "#C0C0C0"],
    imagen: "assets/Logitech_MX_Master_3S/imagen_1.jpg",
  },

  // ========== SMARTWATCHES ==========
  {
    id: "apple-watch-series-9-45",
    categoria: "Smartwatches",
    nombre: "Apple Watch Series 9",
    especificaciones: "S9 SiP | GPS | Pantalla Always-On | 45mm",
    precioPEN: 3499,
    colores: ["#C0C0C0", "#1A1A2E", "#FFB6C1"],
    imagen: "assets/Apple_Watch_Series_9/imagen_1.jpg",
  },
  {
    id: "apple-watch-series-9-41",
    categoria: "Smartwatches",
    nombre: "Apple Watch Series 9",
    especificaciones: "S9 SiP | GPS | Pantalla Always-On | 41mm",
    precioPEN: 3199,
    colores: ["#C0C0C0", "#FFB6C1"],
    imagen: "assets/Apple_Watch_Series_9/imagen_2.jpeg",
  },
  {
    id: "samsung-galaxy-watch-6-44",
    categoria: "Smartwatches",
    nombre: "Samsung Galaxy Watch 6",
    especificaciones: "Exynos W930 | GPS | WearOS | 44mm",
    precioPEN: 2199,
    colores: ["#1A1A2E", "#C0C0C0"],
    imagen: "assets/Samsung_Galaxy_Watch_6/imagen_1.jpg",
  },
  {
    id: "xiaomi-smart-band-8",
    categoria: "Smartwatches",
    nombre: "Xiaomi Smart Band 8",
    especificaciones: "Pantalla AMOLED | 16 dias bateria | GPS",
    precioPEN: 249,
    colores: ["#1A1A2E", "#C0C0C0", "#FFB6C1"],
    imagen: "assets/Xiaomi_Smart_Band_8/imagen_1.jpg",
  },
  {
    id: "xiaomi-smart-band-8-nfc",
    categoria: "Smartwatches",
    nombre: "Xiaomi Smart Band 8",
    especificaciones: "Pantalla AMOLED | 16 dias bateria | NFC",
    precioPEN: 299,
    colores: ["#1A1A2E", "#C0C0C0"],
    imagen: "assets/Xiaomi_Smart_Band_8/imagen_2.jpg",
  },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = productos;
}
